module.exports = {
    CHIRP: "CHIRP",
    CHIRPED: "CHIRPED",
    GOT_SHIRPS: "GOT_SHIRPS",

    GOT_CURRENT_USER: "GOT_CURRENT_USER",
    GOT_USERS: "GOT_USERS",

    FOLLOW: "FOLLOW",
    FOLLOWED: "FOLLOWED",
    
    UNFOLLOW: "UNFOLLOW",
    UNFOLLOWED: "UNFOLLOWED"
};